create table if not exists public.settings (
  id integer primary key default 1 check (id = 1),
  artist_name text,
  hero_tagline text,
  about_text text,
  profile_photo_url text,
  hero_image_url text,
  instagram_url text,
  youtube_url text,
  whatsapp_number text,
  tiktok_url text,
  contact_email text,
  updated_at timestamptz not null default now()
);

create table if not exists public.paintings (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text,
  price numeric(12, 2),
  medium text,
  size text,
  description text,
  status text not null default 'available' check (status in ('available', 'sold', 'featured')),
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.settings enable row level security;
alter table public.paintings enable row level security;

drop policy if exists "Public can read settings" on public.settings;
create policy "Public can read settings" on public.settings for select using (true);

drop policy if exists "Public can read paintings" on public.paintings;
create policy "Public can read paintings" on public.paintings for select using (true);

-- The browser admin uses Supabase Auth. Restrict writes to authenticated users,
-- then limit membership further with a user profile/role policy in production.
drop policy if exists "Authenticated users manage settings" on public.settings;
create policy "Authenticated users manage settings" on public.settings for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated users manage paintings" on public.paintings;
create policy "Authenticated users manage paintings" on public.paintings for all to authenticated using (true) with check (true);

insert into storage.buckets (id, name, public) values ('paintings', 'paintings', true) on conflict (id) do nothing;
drop policy if exists "Public can view painting images" on storage.objects;
create policy "Public can view painting images" on storage.objects for select using (bucket_id = 'paintings');
drop policy if exists "Authenticated users upload painting images" on storage.objects;
create policy "Authenticated users upload painting images" on storage.objects for insert to authenticated with check (bucket_id = 'paintings');
drop policy if exists "Authenticated users delete painting images" on storage.objects;
create policy "Authenticated users delete painting images" on storage.objects for delete to authenticated using (bucket_id = 'paintings');
